# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: golang:1.20
        environment:
          GO111MODULE: "on"
          REDIS_HOST: "localhost:6379"
      - image: redis:latest
    working_directory: /go/src/github.com/iguagile/iguagile-engine
    steps:
      - checkout
      - run: go get golang.org/x/tools/cmd/goimports && diff <(goimports -d $(find . -type f -name '*.go' -not -path "./vendor/*" -not -path "./lib/*")) <(printf "")
      - run: go install golang.org/x/lint/golint@latest && golint -set_exit_status ./...
      - run: go test -bench=. -v ./...
      - run: bash ./fail_test.bash

